<?php
/**
 * DriverOptionsModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BumbalClient\Model;

use \ArrayAccess;

/**
 * DriverOptionsModel Class Doc Comment
 *
 * @category    Class
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DriverOptionsModel implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'DriverOptionsModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'include_driver_record_info' => 'bool',
        'include_driver_meta_data' => 'bool',
        'include_driver_tags' => 'bool',
        'include_driver_tag_type_names' => 'bool',
        'include_addresses' => 'bool',
        'include_driver_links' => 'bool',
        'include_driver_notes' => 'bool',
        'include_driver_note_tags' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'include_driver_record_info' => null,
        'include_driver_meta_data' => null,
        'include_driver_tags' => null,
        'include_driver_tag_type_names' => null,
        'include_addresses' => null,
        'include_driver_links' => null,
        'include_driver_notes' => null,
        'include_driver_note_tags' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'include_driver_record_info' => 'include_driver_record_info',
        'include_driver_meta_data' => 'include_driver_meta_data',
        'include_driver_tags' => 'include_driver_tags',
        'include_driver_tag_type_names' => 'include_driver_tag_type_names',
        'include_addresses' => 'include_addresses',
        'include_driver_links' => 'include_driver_links',
        'include_driver_notes' => 'include_driver_notes',
        'include_driver_note_tags' => 'include_driver_note_tags'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'include_driver_record_info' => 'setIncludeDriverRecordInfo',
        'include_driver_meta_data' => 'setIncludeDriverMetaData',
        'include_driver_tags' => 'setIncludeDriverTags',
        'include_driver_tag_type_names' => 'setIncludeDriverTagTypeNames',
        'include_addresses' => 'setIncludeAddresses',
        'include_driver_links' => 'setIncludeDriverLinks',
        'include_driver_notes' => 'setIncludeDriverNotes',
        'include_driver_note_tags' => 'setIncludeDriverNoteTags'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'include_driver_record_info' => 'getIncludeDriverRecordInfo',
        'include_driver_meta_data' => 'getIncludeDriverMetaData',
        'include_driver_tags' => 'getIncludeDriverTags',
        'include_driver_tag_type_names' => 'getIncludeDriverTagTypeNames',
        'include_addresses' => 'getIncludeAddresses',
        'include_driver_links' => 'getIncludeDriverLinks',
        'include_driver_notes' => 'getIncludeDriverNotes',
        'include_driver_note_tags' => 'getIncludeDriverNoteTags'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['include_driver_record_info'] = isset($data['include_driver_record_info']) ? $data['include_driver_record_info'] : null;
        $this->container['include_driver_meta_data'] = isset($data['include_driver_meta_data']) ? $data['include_driver_meta_data'] : null;
        $this->container['include_driver_tags'] = isset($data['include_driver_tags']) ? $data['include_driver_tags'] : null;
        $this->container['include_driver_tag_type_names'] = isset($data['include_driver_tag_type_names']) ? $data['include_driver_tag_type_names'] : null;
        $this->container['include_addresses'] = isset($data['include_addresses']) ? $data['include_addresses'] : null;
        $this->container['include_driver_links'] = isset($data['include_driver_links']) ? $data['include_driver_links'] : null;
        $this->container['include_driver_notes'] = isset($data['include_driver_notes']) ? $data['include_driver_notes'] : null;
        $this->container['include_driver_note_tags'] = isset($data['include_driver_note_tags']) ? $data['include_driver_note_tags'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets include_driver_record_info
     * @return bool
     */
    public function getIncludeDriverRecordInfo()
    {
        return $this->container['include_driver_record_info'];
    }

    /**
     * Sets include_driver_record_info
     * @param bool $include_driver_record_info 
     * @return $this
     */
    public function setIncludeDriverRecordInfo($include_driver_record_info)
    {
        $this->container['include_driver_record_info'] = $include_driver_record_info;

        return $this;
    }

    /**
     * Gets include_driver_meta_data
     * @return bool
     */
    public function getIncludeDriverMetaData()
    {
        return $this->container['include_driver_meta_data'];
    }

    /**
     * Sets include_driver_meta_data
     * @param bool $include_driver_meta_data 
     * @return $this
     */
    public function setIncludeDriverMetaData($include_driver_meta_data)
    {
        $this->container['include_driver_meta_data'] = $include_driver_meta_data;

        return $this;
    }

    /**
     * Gets include_driver_tags
     * @return bool
     */
    public function getIncludeDriverTags()
    {
        return $this->container['include_driver_tags'];
    }

    /**
     * Sets include_driver_tags
     * @param bool $include_driver_tags 
     * @return $this
     */
    public function setIncludeDriverTags($include_driver_tags)
    {
        $this->container['include_driver_tags'] = $include_driver_tags;

        return $this;
    }

    /**
     * Gets include_driver_tag_type_names
     * @return bool
     */
    public function getIncludeDriverTagTypeNames()
    {
        return $this->container['include_driver_tag_type_names'];
    }

    /**
     * Sets include_driver_tag_type_names
     * @param bool $include_driver_tag_type_names 
     * @return $this
     */
    public function setIncludeDriverTagTypeNames($include_driver_tag_type_names)
    {
        $this->container['include_driver_tag_type_names'] = $include_driver_tag_type_names;

        return $this;
    }

    /**
     * Gets include_addresses
     * @return bool
     */
    public function getIncludeAddresses()
    {
        return $this->container['include_addresses'];
    }

    /**
     * Sets include_addresses
     * @param bool $include_addresses 
     * @return $this
     */
    public function setIncludeAddresses($include_addresses)
    {
        $this->container['include_addresses'] = $include_addresses;

        return $this;
    }

    /**
     * Gets include_driver_links
     * @return bool
     */
    public function getIncludeDriverLinks()
    {
        return $this->container['include_driver_links'];
    }

    /**
     * Sets include_driver_links
     * @param bool $include_driver_links 
     * @return $this
     */
    public function setIncludeDriverLinks($include_driver_links)
    {
        $this->container['include_driver_links'] = $include_driver_links;

        return $this;
    }

    /**
     * Gets include_driver_notes
     * @return bool
     */
    public function getIncludeDriverNotes()
    {
        return $this->container['include_driver_notes'];
    }

    /**
     * Sets include_driver_notes
     * @param bool $include_driver_notes 
     * @return $this
     */
    public function setIncludeDriverNotes($include_driver_notes)
    {
        $this->container['include_driver_notes'] = $include_driver_notes;

        return $this;
    }

    /**
     * Gets include_driver_note_tags
     * @return bool
     */
    public function getIncludeDriverNoteTags()
    {
        return $this->container['include_driver_note_tags'];
    }

    /**
     * Sets include_driver_note_tags
     * @param bool $include_driver_note_tags 
     * @return $this
     */
    public function setIncludeDriverNoteTags($include_driver_note_tags)
    {
        $this->container['include_driver_note_tags'] = $include_driver_note_tags;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\BumbalClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\BumbalClient\ObjectSerializer::sanitizeForSerialization($this));
    }
}


